### ISSUE TITLE
Analytics page for CFDE returned Bad Gateway for the 1st and 3rd panels 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/FAIRshake#134]

**Comment by u8sand** [comment]
This looks like the request takes to long and either nginx or aws times
out. I'll see if i can

1. [ ] Optimize the queries for the graph (I believe they shouldn't take
that long since they are just grouped counts on indexed relationships. I'm
well aware that this particular code can be improved; the insignia itself
hits the same amount of data in the database but that's fine)
2. [ ] Increase the timeout on the nginx gateway
3. [ ] Generate the pages slightly differently so that no sockets are left
waiting (request + poll for response)
